server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

bibliotecapopular.openapi.server-url=${RAILWAY_PUBLIC_DOMAIN:}
